version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "${PORT:-3000}:3000"
    env_file:
      - .env
    volumes:
      - ./logs:/usr/src/app/logs
    depends_on:
      - mongo
    networks:
      - sukoon-network

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - mongo-data:/data/db
    networks:
      - sukoon-network

networks:
  sukoon-network:
    driver: bridge

volumes:
  mongo-data: